events {}

http {
    upstream portal_app {
        server portal:3000;
    }

    upstream jsp_app {
        server lab-jsp:8080;
    }

    upstream php_app {
        server lab-php:80;
    }

    upstream asp_app {
        server lab-aspnet:8080;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://portal_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /labs/jsp/ {
            proxy_pass http://jsp_app/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /labs/php/ {
            proxy_pass http://php_app/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /labs/asp/ {
            proxy_pass http://asp_app/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}